### ISSUE TITLE
No Experience

### ISSUE THREAD

**Issue by Wisecompany** [DaemonUmbra/Simple-Hammers#1]
Minecraft Version: 1.12.2
Mod Version: 1.12.2-1.0.1
Forge Version: 2587

When using a hammer to mine things that drop xp, such as coal, redstone, lapis lazuli, etc., no xp is dropped.

**Comment by DaemonUmbra** [comment]
In all honesty, in my attempt to be simple in the code I think I overlooked this, looking for a solution.

**Comment by Wisecompany** [comment]
So far it's the only thing I've spotted. Ideally, it would look at the total experience that should have been dropped from all of the blocks it mined and drop that.

Otherwise, great job with the mod. It's the simple ones that I appreciate the most.

**Comment by Wisecompany** [comment]
You're fantastic!

**Comment by Konlii** [comment]
It looks like the fix for this was removed when ItemSimpleHammerBase was [rewritten](https://github.com/DaemonUmbra/Simple-Hammers/commit/6f28eb08efa7220ec5d2bfda37ea5c701b86d435) to make room for excavators.

**Comment by DaemonUmbra** [comment]
Yeah, this was my fault in an attempt at refactoring I forgot a line or two of code. I'm considering rewriting a few things outright.

**Comment by Wisecompany** [comment]
It was actually removed here: aa3dea9 (Issue #7 )
