### ISSUE TITLE
No Texture for Creative Tab

### ISSUE THREAD

**Issue by Wisecompany** [DaemonUmbra/Simple-Hammers#5]
See attached image.

![capture](https://user-images.githubusercontent.com/7505105/35119892-fdefe702-fc5b-11e7-9148-522ffd02c0d1.PNG)

**Comment by DaemonUmbra** [comment]
This will be fixed in the next version, when I added the logic for excavators I did a lot of copy-pasta mixed with find and replace the find and replace went a bit rogue and changed the icon from a hammer to an excavator... which does not have a texture yet.
