### ISSUE TITLE
Hammers do not render properly in hand

### ISSUE THREAD

**Issue by Wisecompany** [DaemonUmbra/Simple-Hammers#6]
Hammer handles should render in the hand, like pickaxes do. (see images)
![2018-01-18_18 03 38](https://user-images.githubusercontent.com/7505105/35128032-27388ace-fc7a-11e7-9e75-1210fe452d3a.png)
![2018-01-18_18 03 39](https://user-images.githubusercontent.com/7505105/35128033-276349f8-fc7a-11e7-8eff-bf536d06110c.png)

**Comment by DaemonUmbra** [comment]
Hmm, I was a bit lazy with my research. Will fix with next version.
